### ISSUE TITLE
Error: return code 1

### ISSUE THREAD

**Issue by mdrafiurYU** [Linuxleech/flac-to-mp3#1]
ranscoding 8 Audio files
'/home/student/student-MP3s/gettysburg10-16_19_32.mp3' - return code 1
'/home/student/student-MP3s/OSR_us_000_0014_8k-9_32_43.mp3' - return code 1
'/home/student/student-MP3s/OSR_uk_000_0020_8k-16_20_3.mp3' - return code 1
'/home/student/student-MP3s/84-121123-0001-10_4_53.mp3' - return code 1
'/home/student/student-MP3s/gettysburg10-9_21_40.mp3' - return code 1
'/home/student/student-MP3s/84-121123-0002-10_13_44.mp3' - return code 1
'/home/student/student-MP3s/OSR_uk_000_0020_8k-9_32_37.mp3' - return code 1
'/home/student/student-MP3s/84-121123-0000-10_4_32.mp3' - return code 1
Traceback (most recent call last):
  File "/bin/flac_to_mp3", line 98, in <module>
    subprocess.run(["notify-send", "--urgency=low", MESSAGE])
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'notify-send': 'notify-send'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 145, in apport_excepthook
    os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o640), 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_bin_flac_to_mp3.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/bin/flac_to_mp3", line 98, in <module>
    subprocess.run(["notify-send", "--urgency=low", MESSAGE])
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'notify-send': 'notify-send'

**Comment by bigoper** [comment]
### ERROR
```
Traceback (most recent call last):
  File "/Users/bigoper/Downloads/temp/flac-to-mp3/flac_to_mp3", line 98, in <module>
    subprocess.run(["notify-send", "--urgency=low", MESSAGE])
  File "/Users/bigoper/anaconda3/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Users/bigoper/anaconda3/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/Users/bigoper/anaconda3/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'notify-send': 'notify-send'
```

### INFO
OS: Mac OS

**Comment by Linuxleech** [comment]
Fixed. Should work fine without errors on Mac and Windows now.
