### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by darshuparmar** [Linuxleech/flac-to-mp3#3]
Hi, I am trying to convert .flac files to mp3 but i am getting following error in windows 10.

**The error is as follow :** 

Transcoding 13 Audio files
Traceback (most recent call last):
  File "flac_mp3.py", line 93, in <module>
    JOBS = p.map(converttomp3, PROCESSES)
  File "C:\Users\darsh\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "C:\Users\darsh\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\pool.py", line 768, in get
    raise self._value
  File "C:\Users\darsh\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\darsh\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\pool.py", line 48, in mapstar
    return list(map(*args))
  File "flac_mp3.py", line 28, in converttomp3
    completed = subprocess.run(["ffmpeg",
  File "C:\Users\darsh\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\darsh\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\darsh\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by STS-Mining** [comment]
I know this was a while ago, but i have a fix for this issue

Line 26 
    completed = subprocess.run(["ffmpeg",
    
 change it to this
     completed = subprocess.run(["FFMPEG_PATH",
     
before the converttomp3 function on line 13
add this
FFMPEG_PATH = "Path/to/location/ffmpeg.exe"  # Specify the full path to ffmpeg.exe here

This should fix your problem
